@startuml "Mision Agro"

class Categoria {
    - String name
    + void setName(String name)
    + String getName()
}

class Producto {
    - Long codes
    - String name
    - String description
    - String imageUrl
    + set()
    + get()
}

Categoria "1" o-- "*" Producto
@enduml